# render.yaml (for Render deployment)
services:
  - type: web
    name: telegram-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: DATABASE_URL
        value: sqlite:///music_bot.db
      - key: PORT
        value: 10000
